### ISSUE TITLE
Support operations between Dataset(Slice) and Variable(Slice)

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/dataset#124]
This is not supported in C++ yet. We need it for operations with quantities added in #120. For example

```python
d.subset['alice'] += ds.Variable(1.5, unit=ds.units.m*ds.units.m)
```

I made a start on this in https://github.com/mantidproject/dataset/tree/dataset_binary_with_variable. Whoever picks this up should continue with that branch, adding all the remaining variants (all combinations between `Dataset(Slice)` and `Variable(Slice)`, all relevant operators, and Python exports.

There are some unsolved subtleties to the definition of what such an operation should do. For now, it operates as follows:
- Tag tag-less variables, operate on all `Data::Value` and `Data::Variance` (if applicable, i.e., not for + and -, but for * and /). This would thus ignore event-data, but we can ignore this for now.
- Otherwise, just convert variable into dataset and rely on existing implementation (might not be very useful right now, because this is likely to throw in most cases, but I recommend not touching this at this point).

**Comment by nvaytet** [comment]
This was fixed in #164
