### ISSUE TITLE
demo-part1 notebook fails to be opened

### ISSUE THREAD

**Issue by igudich** [mantidproject/dataset#149]
Get: `Unreadable Notebook: /home/igudich/work/dataset/python/examples/demo-part1.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...',)` trying to open demo-part1 notebook.

**Comment by nvaytet** [comment]
Seems maybe like some strange problem with encoding of new lines? The `\\n` seems weird.
The error message is saying it is failing right at the start of the file, so it's not a problem with left over rogue commas, as some people are suggesting (https://stackoverflow.com/questions/32103772/unreadable-notebook-notjsonerrornotebook-does-not-appear-to-be-json-u-n)

**Comment by nvaytet** [comment]
This was due to having `("alice")` on line 84 instead of `(\"alice\")`
this was fixed in #143
