### ISSUE TITLE
Install nbextensions in docker

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/dataset#173]
Needed to hide exercise solutions. 

See https://stackoverflow.com/a/42056357. Essentially we need:

```
pip install jupyter_contrib_nbextensions
jupyter contrib nbextension install --user

pip install jupyter_nbextensions_configurator
jupyter nbextensions_configurator enable --user
```

**Comment by nvaytet** [comment]
You also need to enable the `exercise2` extension because it won't be enabled by default:
`jupyter nbextension enable exercise2/main`
