### ISSUE TITLE
Order of addition matters for dataset `operator==`

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/dataset#30]
Both `Variable` and `Dimensions` also overload op ==. 

Adding new test to `test_dataset.cpp`
```
TEST(Dataset, equality) {
  Dimensions dimsXY;
  dimsXY.add(Dim::X, 2);
  dimsXY.add(Dim::Y, 2);
  Dimensions dimsYX;
  dimsYX.add(Dim::Y, 2);
  dimsYX.add(Dim::X, 2);
  Dataset d1;
  d1.insert(Data::Value, "xy", dimsXY);
  Dataset d2;
  d2.insert(Data::Value, "yx", dimsXY);
  ASSERT_EQ(d1, d2);
}
```
Order is important. We should either (1) test explicitly for this as above, or (2) change to `Dataset::operator==(const Dataset&)` operator to apply sorting before comparing the above collection of objects.

**Comment by SimonHeybrock** [comment]
I think there are several separate questions here:

- Should datasets with identical variables but different variable order be the same? Definitely! I agree this is a bug, the order should not matter.
- Should variables that are identical after transposition be considered identical? Sounds useful, but I actually think in practice this could cause too much surpising behavior. (I assume your example has a typo, you intended  to use `dimsYX` in `d2`?).
- Should variables with different names (`"xy"` and `"yx"` in your example) be considered equal? I would say no.

**Comment by OwenArnold** [comment]
I agree with your last point and yes typo in example
