### ISSUE TITLE
Variable assignment support.

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/dataset#36]
```python
import numpy as np
from dataset import *
d = Dataset()
```
This works as expected:
```python
d[Data.Value, "a"] = Variable(Data.Value, [Dim.X], np.arange(10))
```
However, support does not allow for the Tag to be resolved from the assignee variable
```python
d["a"] = Variable(Data.Value, [Dim.X], np.arange(10))
```
```
TypeError: __setitem__(): incompatible function arguments
```

**Comment by OwenArnold** [comment]
@SimonHeybrock for comment on current implementation.

**Comment by SimonHeybrock** [comment]
`d["a"]` returns a `DatasetSlice` (which would typically refer to multiple variables such as values and variances), not a single variable, so I do not think what  you are writing in your code example is so useful? It would be confusing if it would potentially delete multiple variables.
